### PR TITLE
Template 2 dataset

### PR DESCRIPTION
**Pull request by dosumis**

### CODE REVIEW

**Comment by dosumis** [comment]
Now all passing apart from class_pub_syn - which is failing due to a database issue (see https://github.com/VirtualFlyBrain/VFB_neo4j/issues/145)

Diffs are a bit hard to read because of code reformatting and tidying up.  

Important changes:  

1. Added reports for 
1. New queries for all datasets and template -> dataset.
1. new queries and dataset TermInfo have new key: dataset_counts: with summary numbers for dataset content.
1. **BREAKING CHANGE**: dataset terminfo 'pub' -> 'pubs' !

**Comment by dosumis** [comment]
Test: [pdb-a is currently passing!](https://travis-ci.org/VirtualFlyBrain/VFB_json_schema/jobs/636449908?utm_medium=notification&utm_source=github_status)

But pdb & pdb-dev are failing with:

Traceback (most recent call last):
  File 

```
"/home/travis/build/VirtualFlyBrain/VFB_json_schema/src/vfb_query_builder/test/query_roller_tests.py", line 11, in test_term_info_query
    print(term_info_export())
  File "/home/travis/build/VirtualFlyBrain/VFB_json_schema/src/vfb_query_builder/query_roller.py", line 604, in term_info_export
    qf = getattr(ql, qm)
AttributeError: 'QueryLibrary' object has no attribute 'anatomical_ind_query'
```

**Comment by dosumis** [comment]
@Robbie1977  - Are you using queries from this branch for dataset queries?

**Comment by Robbie1977** [comment]
used https://github.com/VirtualFlyBrain/geppetto-vfb/blob/development/model/vfb.xmi#L409

**Comment by Robbie1977** [comment]
@dosumis definitely still something: https://travis-ci.org/VirtualFlyBrain/VFB_json_schema/jobs/636449954#L633

**Pull request merged**
